package main

import (
	"fmt"
	"net"
	"strings"
)

// Paths locates the generated material for one run.
type Paths struct {
	CACert     string
	ServerCert string
	ServerKey  string
	CCDDir     string
	AuthHelper string // the ocbridge binary itself, run with --auth
	CredsFile  string
}

// BuildServerConfig renders the openvpn server configuration for one tunnel.
//
// Three things here are load-bearing and were each verified on the rig; see
// tasks/lessons.md before changing them:
//
//   - ifconfig-noexec / route-noexec: there is no interface on this side. The
//     tun device is an inherited socketpair (--dev-node fd:N, our patch).
//   - The client is pushed the gateway-assigned address verbatim via a ccd
//     entry, which is what lets us avoid rewriting addresses and checksums.
//   - push "route <gateway> 255.255.255.255 net_gateway" keeps openconnect's
//     own socket to the Cisco gateway off the tunnel it is carrying. Without
//     it, the moment NetworkManager makes this connection the default route,
//     the transport routes into itself. net_gateway does resolve on the client
//     even though NetworkManager passes --route-noexec (openvpn only skips
//     installing the routes, it still exports them to the --up environment).
//
// Deliberately NOT pushed: redirect-gateway. Under --route-noexec openvpn never
// calls redirect_default_route_to_vpn(), so it is a no-op. NetworkManager
// decides the default route itself from its never-default property, which is
// the "Only use connection for VPN resources" checkbox in the UT VPN editor.
func BuildServerConfig(p *Params, paths Paths, serverIP net.IP, tunFD int, port int, proto string) (string, error) {
	poolStart, poolEnd, err := p.PoolRange(serverIP)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	w("# Generated by ocbridge. Do not edit; it is rewritten on every connect.")
	w("dev tun")
	w("dev-type tun")
	w("dev-node fd:%d", tunFD)
	w("ifconfig-noexec")
	w("route-noexec")
	w("")
	w("mode server")
	w("tls-server")
	w("topology subnet")
	w("ifconfig %s %s", serverIP, p.Netmask)
	w("ifconfig-pool %s %s %s", poolStart, poolEnd, p.Netmask)
	w("client-config-dir %s", paths.CCDDir)
	w("push \"topology subnet\"")
	w("push \"route-gateway %s\"", serverIP)
	w("")
	// Must match what the client is configured with, and the Ubuntu Touch VPN
	// editor writes proto-tcp=yes, so TCP is the default here. A mismatch is
	// invisible from the server side: it simply never sees a packet, and the
	// client reports "Connection refused" against a port that is plainly open
	// for the other protocol.
	if proto == "udp" {
		w("proto udp")
	} else {
		w("proto tcp-server")
	}
	w("local 127.0.0.1")
	w("port %d", port)
	w("")
	w("ca %s", paths.CACert)
	w("cert %s", paths.ServerCert)
	w("key %s", paths.ServerKey)
	w("dh none")
	// The client authenticates with a username and password the app shows the
	// user, so the UT VPN editor needs only ONE file picked (the CA). Client
	// certificates would mean three.
	w("verify-client-cert none")
	w("username-as-common-name")
	w("script-security 2")
	w("setenv OCBRIDGE_CREDS %s", paths.CredsFile)
	// Quoted because openvpn parses this as a command line: the binary plus
	// its --auth flag, with the temporary credentials file appended by
	// openvpn itself. openvpn execve()s it directly, no shell involved --
	// which matters, because a confined click may not execute one.
	w("auth-user-pass-verify \"%s --auth\" via-file", paths.AuthHelper)
	w("")
	// Match the Cisco MTU: whatever the client sends has to fit in the tunnel
	// we are relaying into. The OpenVPN leg itself runs over loopback, so its
	// encapsulation costs CPU but nothing on the wire.
	w("tun-mtu %d", p.MTU)
	w("push \"tun-mtu %d\"", p.MTU)
	w("")

	// NOTE: no bypass route for the Cisco gateway is pushed, and pushing one
	// would be actively harmful.
	//
	// The intuition is that openconnect's own socket to the gateway must be
	// kept off the tunnel it is carrying, and openvpn's `net_gateway` keyword
	// resolves correctly for that. But NetworkManager applies every route a
	// VPN pushes to the VPN *device*, so the rule lands as
	//
	//	198.18.110.147 via <lan-gateway> dev tun0
	//
	// -- the gateway routed straight into the tunnel. Observed on device:
	// bytes_out climbing, bytes_in stuck at 0, and nothing reachable at all.
	// A pushed route can never be a bypass; it is the opposite of one.
	//
	// The transport stays off the tunnel simply by not being routed onto it,
	// which holds as long as there is no default route via the VPN -- that is
	// the user's "Only use connection for VPN resources" checkbox. Full-tunnel
	// mode cannot work here: NetworkManager protects the VPN's own remote
	// (127.0.0.1, useless to us) and a plugin cannot install a route on the
	// physical device. See README, "Known limitations".
	// SplitRoutes, not Splits: the gateway's own address is punched out of any
	// route that would otherwise carry it into the tunnel.
	for _, r := range p.SplitRoutes() {
		w("push \"route %s %s\"", r.Network, r.Mask)
	}
	for _, d := range p.DNS {
		w("push \"dhcp-option DNS %s\"", d)
	}
	if p.Domain != "" {
		w("push \"dhcp-option DOMAIN %s\"", p.Domain)
	}
	w("")
	w("keepalive 10 60")
	w("persist-key")
	w("verb 3")
	return b.String(), nil
}

// BuildCCD renders the per-client directives. Note this is the DEFAULT file:
// ccd-exclusive is deliberately NOT set on the server, because that mode
// ignores DEFAULT and demands a file named after the common name.
func BuildCCD(p *Params) string {
	return fmt.Sprintf("# Generated by ocbridge.\nifconfig-push %s %s\n", p.Address, p.Netmask)
}
